### ISSUE TITLE
Interesting behaviour

### ISSUE THREAD

**Issue by enverunal** [mmcshane/leftright#3]
Hi i have decided to test leftright implementation of yours.

write thread updates leftright protected Big struct.
read thread reads updated values and checks if read struct is half updated.

I have run this test on x86_64 cpu and i read half updated values.

I dont think this is the expected behaviour but want to ask anyways.
Is this expected behaviour?

Sample output
**failed 23096 23097 23097 23097
failed 72977 72977 72977 72979
failed 109959 109959 109959 109960**

Here is the test code.
```
struct Big
{
private:
	alignas(std::hardware_destructive_interference_size) int a1{};
	alignas(std::hardware_destructive_interference_size) int a2{};
	alignas(std::hardware_destructive_interference_size) int a3{};
	alignas(std::hardware_destructive_interference_size) int a4{};

public:
	void add1()
	{
		a1 += 1;
		a2 += 1;
		a3 += 1;
		a4 += 1;
	}

	void print() const
	{
		std::cout << a1 << ' ' << a2 << ' ' << a3 << ' ' << a4 << std::endl;
	}

	void check() const
	{
		if ((a1 == a2) && (a1 == a3) && (a1 == a4))
		{
		}
		else
		{
			std::cout << "failed ";
			this->print();
		}
	}
};

template <typename T>
struct leftright_wrap
{
	mpm::leftright<T> lr;

	auto read() const noexcept
	{
		return lr.observe([](const auto &val) noexcept
						  { return val; });
	}

	auto write(const T &t) noexcept
	{
		lr.modify([&t](auto &val) noexcept
				  { val = t; });
	}
};

int main()
{

	leftright_wrap<Big> lr;

	std::thread read_([&lr]
					  {
						  while (true)
						  {
							  auto a = lr.read();
							  a.check(); //! should not see half updated value
						  }
					  }

	);

	std::thread write_([&lr]
					   {
						   Big big{};
						   while (true)
						   {
							   big.add1();
							   lr.write(big);
						   }
					   }

	);

	read_.join();
	write_.join();
}
```

**Comment by mmcshane** [comment]
This happens because the ref made available to the `observe` callback is being allowed to escape the scope of that function call. Using that ref outside of the `observe` callback will access one of the two underlying values (left or right), potentially while that value is being written. Here you're seeing a partial write of that value.

**Comment by AndrewJD79** [comment]
@mmcshane, could you please give more details what ref did you mean.

**Comment by AndrewJD79** [comment]
BTW, problem is not reproducing if change memory model in lines 294. 301 to `std::memory_order_seq_cst`

**Comment by mmcshane** [comment]
Looks like I misunderstood the semantics of `auto`. Sorry - I left C++ before `auto` became usable.

I am able to reproduce the problem and eliminate it with the change that you suggest, @AndrewJD79. However I'm suspicious of the change in that the reads/writes to that single location should see each other already because of the release/acquire being used. My concern is that the true source of the problem is actually elsewhere - perhaps in the way the reader registry makes the presence of readers visible.

**Comment by AndrewJD79** [comment]
The access to `m_leftright` in `observe` also has to have memory order `memory_order_seq_cst` because seq_cst works only with others seq_cst load/stores.
I think seq_cst has perfect sense here since Release-Acquire doesn't establsih total modificatin order. See highlighted section from memory ordering description:

> Release-Acquire ordering
If an atomic store in thread A is tagged memory_order_release, an atomic load in thread B from the same variable is tagged memory_order_acquire, and the load in thread B reads a value written by the store in thread A, then the store in thread A synchronizes-with the load in thread B.
All memory writes (including non-atomic and relaxed atomic) that happened-before the atomic store from the point of view of thread A, become visible side-effects in thread B. That is, once the atomic load is completed, thread B is guaranteed to see everything thread A wrote to memory. **This promise only holds if B actually returns the value that A stored, or a value from later in the release sequence**.  

The store `m_leftright.store(read_right, std::memory_order_release);` doesn't make new value of `m_leftright` become immediately avaible in the reader thread. It only guarantee that when it become visible all previous writes will be available too. Therefore, reader got stale value of m_leftright and observe partially updated values.  

I also checked those changes with [Relacy Race Detector](https://github.com/dvyukov/relacy#relacy-race-detector) and [ThreadSanitizer](https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual). 
For some reasons, RRD continued reporting data races until I made 'atomic_reader_registry' also use seq_cst memory order. ThreadSanitizer and the test itself don't report any problems. I cannot explain why RRD complains, and I suspect the code works for x86 but may not work for weaker CPU architectures.

**Comment by enverunal** [comment]
```
template <typename T, typename R>
template <typename F>
typename std::result_of<F(const T&)>::type
basic_leftright<T, R>::observe(F f) const
    noexcept(noexcept(f(std::declval<const T&>())))
{
    std::size_t idx = m_registry_index.load(std::memory_order_acquire);
    /*
        Reader is here. Nothing will prevent writer from changing the registery index. 
        Because we havent called the scoped_read_indication yet.
    */
    scoped_read_indication sri(m_reader_registries[idx]);
    return read_left == m_leftright.load(std::memory_order_acquire)
        ? f(m_left)
        : f(m_right);
}
```

We need to somehow achieve following code. 

```
template <typename T, typename R>
template <typename F>
typename std::result_of<F(const T&)>::type
basic_leftright<T, R>::observe(F f) const
    noexcept(noexcept(f(std::declval<const T&>())))
{
    // these two statements are atomically executed
atomic {
      std::size_t idx = m_registry_index.load(std::memory_order_acquire);
      scoped_read_indication sri(m_reader_registries[idx]);
}
    return read_left == m_leftright.load(std::memory_order_acquire)
        ? f(m_left)
        : f(m_right);
}
```

**Comment by AndrewJD79** [comment]
[Reading ](https://github.com/mmcshane/leftright/blob/master/include/mpm/leftright.h#L278 ) from m_leftright also must be seq_cst. The seq_cst [cannot be mixed ](https://en.cppreference.com/w/cpp/atomic/memory_order#Sequentially-consistent_ordering) with other types of ordering.
